### ISSUE TITLE
关于model_joint_small_1e64.pt

### ISSUE THREAD

**Issue by HXYM** [jianliu-ml/Multimedia-EE#7]
请问您能提供一下"/home/jliu/research/5.MMEE/model_checkpoint/model_joint_small_1e64.pt"这个文件吗，非常感谢

**Comment by BudBudding** [comment]
您好，请问一下 您那边有train.py文件中提到的'data/data.pk'吗？ 我还有一个疑问点，该模型的loss都是基于BertNER模型进行计算的，但是论文中，提出的引入对比学习，关于这个您有什么见解吗？

**Comment by HXYM** [comment]
> 您好，请问一下 您那边有train.py文件中提到的'data/data.pk'吗？ 我还有一个疑问点，该模型的loss都是基于BertNER模型进行计算的，但是论文中，提出的引入对比学习，关于这个您有什么见解吗？

data.pk文件用作者提供的preprocess文件进行生成，但是生成这个文件需要作者那边通过ACE2005生成的训练文件以及一个通过CLIP预训练好的model文件，这两个文件作者都没有提供，这个model文件”model_joint_small_1e64.pt“可能就是通过对比学习训练的文件，不知道作者是通过自己方式借鉴CLIP训练出来的还是直接用的CLIP，我给作者发送邮件，作者接收到邮件确不回复，使我不得不怀疑他研究工作的真实性，如果你有什么新的发现可以再和我交流吗，我的QQ：879834803
